#
# ----------------------------------------------------------------------
#     SMP T-Kernel
#
#     Copyright (C) 2007-2010 Ken Sakamura. All Rights Reserved.
#     SMP T-Kernel is distributed under the T-License for SMP T-Kernel.
# ----------------------------------------------------------------------
#
#     Version:   1.00.01
#     Released by T-Engine Forum(http://www.t-engine.org) at 2010/02/19.
#
# ----------------------------------------------------------------------
#

#
#	Makefile for gmake
#	tstdlib (included from sysmain)
#

# source files
SRC	+= bitop.c

# source file path
VPATH   += ../../../tstdlib
HEADER  += ../../../tstdlib

# Manager and Driver objects
I_OBJ	+=
